language: node_js
node_js:
  - "10"
script:
  - yarn test
  - yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  skip_cleanup: true
  api_key:
    secure: A9L0hgLF+ccDQsyELTXFZizk2dbgl4xSYa/C1KYEy2g0zCsoP9+ERFaHxLF03NzJtrORz9H+i5fylY08HccltmJj+CEDJODQnmKu0tHMEm4gMmw0FEV9ew9xfUupegNIcfDY8zPLW+MprQhxOScePydAfj6hl0j541AOVMLSNR6kzeRYwM97P43adGfpzgzd1llWR2NEzkH8UH/esMVPpt9PfFz4ei24X4cP0iL1Ebaih+Tz1ekN3I3T/jzyv3sbggkFVMTqZiAIAWhN6HiAwB8dgOy3aMXV5pr4T2yTre+1FhetPEW4bXJTkFGN+rHVYk6uWyAf5ogrlGfVrub8AKcb55e69siOccjqpwEB6QuvQ0x/LJBovhZ36dsE2/ID2ZXzda3BOstCIyPwUPUteg9PgInYfdv2q61yl3wAuwfp0qgy0v0BY4YGDDosVY5kBkKxjNNCgmi6A3bvfJNvapcMUMg0xugyO6xqwvcTeTgMTdmq8HuhWKMh795oF4640YJ6rP0iYk73LBQ5mX18WiOFyoPryQMRBGBcyWnj0R4yJLOI0M2hxrYvD8zfYL6cGWGw7CBUQtYaj09jjchX32IMDRKgld0BpXo+bS9OXVxgUwVRMrt+NWSaJbD9qi0Dp4wivbH3y2y+rrFBcfICf9EeFdg6H+pXqNI4KWllk4o=
  on:
    tags: true
    repo: uwdata/falcon
