language: node_js
node_js:
- '10'
script:
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: uwdata/falcon
  api_key:
    secure: NR/ekH3Lnk9QVjlIRnVeNBVdtVNzqI8fjrf7LV8Y2V6qUnVobNPMtnWrsqghOBm24cKbN8ATtmAVk5CY2A+cq9H/Yf+F8Pneebr1UvVJSw5MxD7Mmv/2z9pj6ZwOiSwH6G+4F3qfo6fOCSzgIqSuasZOvI3QhjwwUHfiPxQxAaTQ0Z8qZQGUzK116nKc2K4Nn4nBSYtV4/SU9TNMAzK4v0A2KP62DoII/APTKsJEp7+Wa2n6BjZ0kETuItFbKSPCQ2eGhkFn7q3g6Il/8Huo5jkXinBKXum0OUIpY/rHMin8TjrkORZEXPH2liBBU4ptzXTJpp7o7Gso51W+grtL8QpShby1JUgRt+Ja1lsv6vYqD9kMnWEf6PskJceL3KP/LDAEQhzZlS8tFoggkp90nmY0KxHqvX3I12GgO1QerfcVVEko64YFygOyE3b8bDZTKf4ihzO5IPOt1E5xpTAxloPtyYNc7itjnKG1kZx8/vR9S0QEXUHR3/PQKY610dX8j5KiSjSREbz02Z6wUitYrlLQL5q7R55NIBZbPKY7/+MbHlVburT+TpaW8vuW968ot62xKLjVEnneD2ptpji/uFMooKeTOmWa/s1QjerK65EKsAewQqeQMkZEOhApamta567Uq6J217zjN24VRK03XIlJHggAgiWq6Mj1ebWInqQ=
