language: node_js
node_js:
- '10'
script:
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: uwdata/falcon
  api_key:
    secure: VehRiMlgB/UqPjbvUmGdaYZiCksKWLa6sZZ+bpRGh0Uc3F0Wr+rlQ7q1JGFSX4darBEgcJBKULBjp+lOQD4wP3JUNW5kElli/VBvRsyo8cOsDbYpm0+/qKbSonZkxcvYeTa5cjU5WkJnJ+Lf3bxt7Q00iQOok52vLV/Aag4s5jLs7W7WPt6iUC9oyEvJ3v5TiMShBzjXkm6clk9ggCWYeaEZBS8np8fAcIpor7EvMgBO8vJAKHASdTj9kTXhXN01h+sPw6MA2In+3lrb08Jl4VcaiqKbDU2zoXmZkOYXWpPYbscTHkk7YY1x5msAeaAu2FhnYfhJtPbLi30g2EZADAoGzsxdn07rCfki+rhvXf3lTU4S2k8GoSYcWp2yM3EpWho+RZqaxFRKMyoLA9A5aHwuSF8tgYoYBaTbTFmmWdAiDW3FIVJHSdkwAEnf3jiisdqgezIvDIPO5CVJCeyCPJiR587O+k3VrBBTqIgrqzYX3leRsNDMdgqHgzrDQEYKSdIFcoA4LiyqVZeGVXMS78RZWJu+i71yoVMs0bTuO15XUep+oo7cslw9aOuRT12ycT9BT8Yp0HynT5GYWIvRRDcCTnX3NvNdKfQzLdUpScqdT+EZ0lokyqMIKqhoCJ6y/1b7mXvR/cozjHRfF+VdIO+UY8uV/Wr/jeCg3ExrcNk=
