language: node_js
node_js:
- '10'
script:
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: uwdata/falcon
  api_key:
    secure: K8wkFhSzvk4G80IX0BDlTVD+J5BSqD212MDglRnkJvaSSZt+ln42+vtlif/KtBplYAB92zt+uNlNsRTgG4fcrYx5Ynwxf4zzE9BwRlrdwg0LuHOU9cxt8zjVUJ3dEhpiQv0/8Vx8DJG3uX5JjgCxbrS3xfNt9e+VpyRB/JenPx5x5AVBZLwbZSyWVYz840X6cwxBSALFW7c7kjvyh1fxp4bKzvAdcruLvCVRnh/DIQz8sB5Twu7079GgyrubrMqvCTKvC9oXT8L60IlJOrQQlM6IwxHZXIYop0p12eSQUTmt1PI6iLpeYKjEqxrQ5bOlsOu6oWpq0tDFWgfexKMhuVcX+hdjys53TymkyqVe/7e6+acx8bLwp2IWm1fsfb4vymFyJYgpcHMm3HE7iOWTN1cbnVozT/gXtWqzGcTnukQyX0UZOMLNNVwNM32Lg4gnLPVn5LBOfbmFJppPSij3MYGoEZKDLEM7PSGqLtsfcpUcTxlvu5/CzqLcja82ovfYHJup6+OHmC1dP0m93L3Ly6Cw7cMGq1a/6+uA41GE7X0rv4dt4BDrt9EnjYxLYw6os++F9vnfDGaoq99AX+8jciWOhDodii8shuMlfNJnMrHiYg2BxHkBJOMX9hvstXVIVUItAYQP6COURP7i/BNIY54kolWvEeynUBiz23uqoKE=
