language: node_js
node_js:
- '10'
script:
- yarn test
- yarn build
cache: yarn
deploy:
  provider: npm
  email: domoritz@gmail.com
  skip_cleanup: true
  on:
    tags: true
    repo: uwdata/falcon
  api_key:
    secure: GLncYp9wZyXZOfA5Zc4dtSHSju5edizvPNZQuhURpb1GIrbbppmbKgouDaA3JuYdmdbTC66JoCE+6274Ziv1RN7zkCb8wJd9cFgei6MYu/s0ESjfmLbu0pW6aR6YX6ZBCKa4SE1i7AjwZn9Z6MaaZTVqIjEhddS+DL7EFyy0P98o7AUrdvouxY97bGCa2jktadABIba1WKP1V7WXDywKUg2n+6a6iRm00fgxec6pyx9zhnD4kq/W6f4udu1DyYJ2kNQDJT0Mqm4XzoUzrFhATNiwC7Z7ILMf65/ZFErmbStoa5p4mt0AwWmkr1DR1cK+pEeG8e1uuPpke85nhz0OIcdodqUHlrpJz6BBRgH0CEPwG1LqUOjKC6UZYiLvQ+y32PCRY/C6WzkaETgku6/Y08wsCCvQwaKjD/P7vBdnzJajyoJih6hqM8g6m7gryq5yf5DYtMOB8LEZ65yVoIAQVV6yDDCjaZbHAuS2A/QF2TDOPRIdjw3fe8T47xzJlRBq9Wm1UFBcEwCoZChd+3cFdc3ZJIna/xhalw6yL94XJhHMpK+TJ2Mk7DpviLYYuH1O9OcN8ncfkp41t1d8i360M68J4lfZ+X4RmNJ2N3KHbEA1Xq1meF/2LVCiJOYEyVx7KAKjFMJZmeRHfmMc+PHO5CTlWKQyH+D++/vVlpFbNPQ=
